const ALLOWED_SOURCE = /(^|\.)dramafren\.org$/i;
const ALLOWED_ORIGINS = new Set(["https://bingebox.bond","https://www.bingebox.bond"]);
function cors(req){const origin=req.headers.get("Origin")||"";return{"Access-Control-Allow-Origin":ALLOWED_ORIGINS.has(origin)?origin:"https://bingebox.bond","Access-Control-Allow-Headers":"Authorization, Content-Type","Access-Control-Allow-Methods":"GET, POST, OPTIONS","Access-Control-Max-Age":"86400",Vary:"Origin"}}
function json(req,data,status=200){return new Response(JSON.stringify(data),{status,headers:{...cors(req),"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store"}})}
function abs(value,base){try{const u=new URL(String(value).replace(/&amp;/g,"&"),base);return u.protocol==="https:"?u.href:null}catch{return null}}
function epno(value){const m=String(value||"").match(/(?:episode|ep)[\s._#:/="'-]*(\d{1,4})/i);return m?Number(m[1]):0}
function provider(url){try{const h=new URL(url).hostname.toLowerCase();if(h.includes("upnshare")||h.endsWith(".upn.one"))return"upnshare";if(h.includes("ok.ru"))return"okru";if(h.includes("youtube")||h==="youtu.be")return"youtube";if(h.includes("vimeo"))return"vimeo";return"external"}catch{return"external"}}
function sourceType(url){return /\.(mp4|webm|m3u8|mov)(?:$|\?)/i.test(url)?"direct":"embed"}
async function authorized(req,env){try{const token=(req.headers.get("Authorization")||"").replace(/^Bearer\s+/i,"");if(!token)return false;if(!env.SUPABASE_URL||!env.SUPABASE_ANON_KEY){console.error("Missing Supabase environment variables");return false}const headers={Authorization:`Bearer ${token}`,apikey:env.SUPABASE_ANON_KEY,Accept:"application/json"};const ur=await fetch(`${env.SUPABASE_URL}/auth/v1/user`,{headers});if(!ur.ok){console.error("Supabase auth failed:",ur.status);return false}const user=await ur.json();if(!user?.id)return false;const ar=await fetch(`${env.SUPABASE_URL}/rest/v1/admins?user_id=eq.${encodeURIComponent(user.id)}&select=user_id&limit=1`,{headers});if(!ar.ok){console.error("Admin lookup failed:",ar.status);return false}const admins=await ar.json();return Array.isArray(admins)&&admins.length>0}catch(error){console.error("Authorization error:",error);return false}}
async function fetchPage(url){const u=new URL(url);if(u.protocol!=="https:"||!ALLOWED_SOURCE.test(u.hostname))throw new Error("Only authorized DramaFren URLs are accepted.");const response=await fetch(u.href,{headers:{Accept:"text/html,application/xhtml+xml","User-Agent":"BingeBox Authorized Importer/1.2"},redirect:"follow"});if(!response.ok)throw new Error(`DramaFren returned HTTP ${response.status}.`);const contentType=(response.headers.get("content-type")||"").toLowerCase();if(!contentType.includes("html")&&!contentType.includes("xhtml"))throw new Error("DramaFren did not return an HTML page.");const text=await response.text();if(text.length>5000000)throw new Error("Source page is too large.");return{text,url:response.url}}
function discoverEpisodes(html,base,input){const map=new Map();function add(href,label=""){const url=abs(href,base);if(!url)return;const u=new URL(url);if(!ALLOWED_SOURCE.test(u.hostname))return;const number=epno(label)||Number(u.searchParams.get("ep"))||epno(u.pathname);if(!number)return;if(!u.searchParams.get("ep")&&!/watch|episode/i.test(u.pathname+u.search))return;if(!map.has(number))map.set(number,url)}for(const match of html.matchAll(/<a\b[^>]*href\s*=\s*["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi))add(match[1],match[2].replace(/<[^>]+>/g," "));const inputUrl=new URL(input),currentEpisode=Number(inputUrl.searchParams.get("ep"))||epno(input)||1;map.set(currentEpisode,input);const dramaId=inputUrl.searchParams.get("id");if(dramaId){for(const match of html.matchAll(/(?:episode|ep)[\s"'=:._#/-]*(\d{1,4})/gi)){const number=Number(match[1]);if(!number||number<1||number>500)continue;const episodeUrl=new URL(input);episodeUrl.searchParams.set("ep",String(number));map.set(number,episodeUrl.href)}}return[...map].sort((a,b)=>a[0]-b[0]).slice(0,500).map(([episode_number,url])=>({episode_number,url}))}
function discoverPlayers(html,base,episodeNumber){const results=[],seen=new Set();function add(raw){const url=abs(raw,base);if(!url||seen.has(url))return;let u;try{u=new URL(url)}catch{return}if(ALLOWED_SOURCE.test(u.hostname)&&(/page=watch/i.test(u.search)||/\/watch\b/i.test(u.pathname)))return;seen.add(url);results.push({episode_number:episodeNumber,url,provider:provider(url),source_type:sourceType(url)})}for(const match of html.matchAll(/<iframe\b[^>]*\bsrc\s*=\s*["']([^"']+)["']/gi))add(match[1]);for(const match of html.matchAll(/<(?:video|source)\b[^>]*\bsrc\s*=\s*["']([^"']+)["']/gi))add(match[1]);for(const match of html.matchAll(/https:\/\/[^\s"'<>\\]+?\.(?:m3u8|mp4|webm|mov)(?:\?[^\s"'<>\\]*)?/gi))add(match[0]);return results}
async function runImporter(input,retryEpisodes=[]){let first=null,episodes=[];if(Array.isArray(retryEpisodes)&&retryEpisodes.length){episodes=retryEpisodes.map(x=>({episode_number:Number(x.episode_number)||0,url:String(x.url||"")})).filter(x=>x.episode_number>0&&x.url)}else{first=await fetchPage(input);episodes=discoverEpisodes(first.text,first.url,input)}const items=[],failures=[],queue=[...episodes];let checked=0;const workers=Array.from({length:Math.min(5,Math.max(1,queue.length))},async()=>{while(queue.length){const episode=queue.shift();if(!episode)break;try{const page=first&&episode.url===first.url?first:await fetchPage(episode.url);items.push(...discoverPlayers(page.text,page.url,episode.episode_number))}catch(error){const message=error?.message||String(error||"Episode fetch failed.");console.error(`Episode ${episode.episode_number} failed:`,message);failures.push({episode_number:episode.episode_number,url:episode.url,error:message})}checked++}});await Promise.all(workers);items.sort((a,b)=>a.episode_number-b.episode_number);failures.sort((a,b)=>a.episode_number-b.episode_number);return{items,failures,episodes_checked:checked,episodes_discovered:episodes.length,sources_found:items.length}}
export default{async fetch(req,env){const origin=req.headers.get("Origin")||"";if(req.method==="OPTIONS"){if(origin&&!ALLOWED_ORIGINS.has(origin))return new Response(null,{status:403,headers:cors(req)});return new Response(null,{status:204,headers:cors(req)})}const url=new URL(req.url);if(url.pathname==="/"&&req.method==="GET")return json(req,{ok:true,service:"bingebox-import",version:"21.9.0",supabase_url:Boolean(env.SUPABASE_URL),supabase_key:Boolean(env.SUPABASE_ANON_KEY)});if(url.pathname!=="/admin/import-series"||req.method!=="POST")return json(req,{error:"Not found."},404);if(origin&&!ALLOWED_ORIGINS.has(origin))return json(req,{error:`Origin not allowed: ${origin}`},403);if(!(await authorized(req,env)))return json(req,{error:"Admin authorization failed."},401);try{const body=await req.json();if(!body?.url)return json(req,{error:"DramaFren URL is required."},400);let source;try{source=new URL(body.url)}catch{return json(req,{error:"Invalid URL."},400)}if(source.protocol!=="https:"||!ALLOWED_SOURCE.test(source.hostname))return json(req,{error:"Use an authorized DramaFren HTTPS URL."},400);const result=await runImporter(source.href,Array.isArray(body.retry_episodes)?body.retry_episodes:[]);return json(req,{ok:true,...result})}catch(error){console.error("IMPORT_ERROR:",error);return json(req,{error:error?.message||"Import failed."},422)}}};
