
create table if not exists public.source_sync_state (
  source_key text primary key,
  baseline_established_at timestamptz,
  last_successful_scan_at timestamptz,
  last_seen_source_id text,
  last_seen_timestamp timestamptz,
  sync_watermark timestamptz,
  catalog_count integer not null default 0,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.source_sync_state enable row level security;
revoke all on public.source_sync_state from anon, authenticated;
grant select, insert, update, delete on public.source_sync_state to service_role;

create table if not exists public.sync_queue (
  id uuid primary key default gen_random_uuid(),
  source_key text not null,
  source_content_id text not null,
  job_type text not null check (job_type in ('title_new','title_changed','episode_count_changed','resolve_episodes','resolve_media')),
  idempotency_key text not null unique,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'pending'
    check (status in ('pending','processing','retry_wait','completed','failed','blocked')),
  priority integer not null default 100,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  claimed_by uuid,
  claimed_at timestamptz,
  heartbeat_at timestamptz,
  lease_expires_at timestamptz,
  next_retry_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  completed_at timestamptz
);

alter table public.sync_queue enable row level security;
revoke all on public.sync_queue from anon, authenticated;
grant select, insert, update, delete on public.sync_queue to service_role;

create index if not exists sync_queue_work_idx
  on public.sync_queue(status, priority, coalesce(next_retry_at, created_at), created_at)
  where status in ('pending','retry_wait','processing');

create index if not exists sync_queue_source_idx
  on public.sync_queue(source_key, source_content_id, created_at desc);

create table if not exists public.sync_events (
  id bigint generated by default as identity primary key,
  source_key text not null,
  event_type text not null,
  source_content_id text,
  details jsonb not null default '{}'::jsonb,
  occurred_at timestamptz not null default now()
);

alter table public.sync_events enable row level security;
revoke all on public.sync_events from anon, authenticated;
grant select, insert, update, delete on public.sync_events to service_role;

create index if not exists sync_events_source_time_idx
  on public.sync_events(source_key, occurred_at desc);

create or replace function public.claim_sync_queue_job(
  p_worker uuid,
  p_lease_seconds integer default 120
)
returns setof public.sync_queue
language plpgsql
security invoker
set search_path=public
as $$
begin
  if p_worker is null then
    raise exception 'worker token is required';
  end if;

  return query
  with candidate as (
    select q.id
    from public.sync_queue q
    where (
      q.status = 'pending'
      or (q.status='retry_wait' and coalesce(q.next_retry_at,'-infinity'::timestamptz) <= now())
      or (
        q.status='processing'
        and coalesce(q.lease_expires_at,q.heartbeat_at + interval '3 minutes','-infinity'::timestamptz) <= now()
      )
    )
    order by q.priority asc, q.created_at asc
    for update skip locked
    limit 1
  )
  update public.sync_queue q
  set status='processing',
      attempt_count=q.attempt_count+1,
      claimed_by=p_worker,
      claimed_at=now(),
      heartbeat_at=now(),
      lease_expires_at=now()+make_interval(secs=>greatest(30,least(coalesce(p_lease_seconds,120),300))),
      updated_at=now()
  from candidate c
  where q.id=c.id
  returning q.*;
end;
$$;

revoke all on function public.claim_sync_queue_job(uuid,integer) from public,anon,authenticated;
grant execute on function public.claim_sync_queue_job(uuid,integer) to service_role;

insert into public.source_sync_state (
  source_key, baseline_established_at, last_successful_scan_at,
  last_seen_source_id, last_seen_timestamp, sync_watermark,
  catalog_count, metadata, updated_at
)
select
  'dramafren_webfic',
  now(),
  max(last_fetched_at),
  (select book_id from public.dramafren_catalog_queue order by shelf_time desc nulls last,book_id desc limit 1),
  max(shelf_time),
  now(),
  count(*),
  jsonb_build_object(
    'baseline_reason','Initial 3000-title Webfic browse catalog plus prior indexed/recommendation discoveries',
    'future_only',true
  ),
  now()
from public.dramafren_catalog_queue
on conflict (source_key) do update
set baseline_established_at=coalesce(public.source_sync_state.baseline_established_at,excluded.baseline_established_at),
    last_successful_scan_at=excluded.last_successful_scan_at,
    last_seen_source_id=excluded.last_seen_source_id,
    last_seen_timestamp=excluded.last_seen_timestamp,
    sync_watermark=coalesce(public.source_sync_state.sync_watermark,excluded.sync_watermark),
    catalog_count=excluded.catalog_count,
    metadata=public.source_sync_state.metadata || excluded.metadata,
    updated_at=now();

insert into public.sync_events(source_key,event_type,details)
values (
  'dramafren_webfic',
  'baseline_established',
  jsonb_build_object(
    'catalog_count',(select count(*) from public.dramafren_catalog_queue),
    'future_only',true,
    'note','Historical catalog recorded as baseline; no historical flood queued.'
  )
);
